#!/bin/sh


serverKill=$(ps aux | grep "./server$" | awk '{print $2}')
kill $serverKill
clientKill=$(ps aux | grep "./client " | awk '{print $2}')
kill $clientKill
proxyKill=$(ps aux | grep "rdcc_proxy.py" | awk '{print $2}')
kill $proxyKill
