#!/bin/sh
make clean && make build
./kill
touch output.txt
clear

TT=${1:-rd}
LR=${2:-0.1}

python3 ./rdcc_proxy.py --test_type $TT -l $LR > /dev/null &
proxyPID=$!

time ./server &
serverPID=$!

./client $3 &
clientPID=$!



wait $serverPID

kill $proxyPID
kill $clientPID

if [ "$(diff $3 output.txt)" = "" ]; then
    echo "passed"
else
    echo "failed"
fi

exit
