#!/bin/sh
make clean && make build
./kill
touch output.txt
rm graph.csv
clear

TT=${1:-rd}
LR=${2:-0.1}

python3 ./rdcc_proxy.py --test_type $TT -l $LR > /dev/null &
proxyPID=$!

time ./server &
serverPID=$!

./client input.txt &
clientPID=$!

INPUT=$(ls -l | grep "input" | awk '{print $5}')
i=0

while true; do
    OUTPUT=$(ls -l | grep 'output' | awk '{print $5}')
    if [ "$INPUT" = "$OUTPUT" ]; then
        if [ "$(diff input.txt output.txt)" = "" ]; then
            echo "passed"
        else
            echo "failed"
        fi
        break
    else
        echo "$i,$OUTPUT" | tee -a graph.csv
        ((i++))
    fi
done

wait $serverPID

kill $proxyPID
kill $clientPID

if [ "$(diff input.txt output.txt)" = "" ]; then
    echo "passed"
else
    echo "failed"
fi

exit
